INSERT INTO CATEGORIA (NOMBRE, DESCRIPCION, ESTADO)
VALUES
  ('Categoria 1', 'Descripcion de la Categoria 1', 1),
  ('Categoria 2', 'Descripcion de la Categoria 2', 0),
  ('Categoria 3', 'Descripcion de la Categoria 3', 1),
  ('Categoria 4', 'Descripcion de la Categoria 4', 1),
  ('Categoria 5', 'Descripcion de la Categoria 5', 1),
  ('Categoria 6', 'Descripcion de la Categoria 6', 0),
  ('Categoria 7', 'Descripcion de la Categoria 7', 1),
  ('Categoria 8', 'Descripcion de la Categoria 8', 0),
  ('Categoria 9', 'Descripcion de la Categoria 9', 1),
  ('Categoria 10', 'Descripcion de la Categoria 10', 1);

INSERT INTO USUARIO (CORREO_ELECTRONICO, NOMBRE, APELLIDO, ESTADO)
VALUES
  ('usuario1@example.com', 'Juan', 'Pérez', 1),
  ('usuario2@example.com', 'Maria', 'González', 0),
  ('usuario3@example.com', 'Carlos', 'Ramirez', 1),
  ('usuario4@example.com', 'Laura', 'Lopez', 1),
  ('usuario5@example.com', 'Pedro', 'Martinez', 1),
  ('usuario6@example.com', 'Ana', 'Fernández', 0),
  ('usuario7@example.com', 'Luis', 'Gomez', 1),
  ('usuario8@example.com', 'Sofia', 'Rodriguez', 0),
  ('usuario9@example.com', 'Alejandro', 'Hernández', 1),
  ('usuario10@example.com', 'Lucia', 'Torres', 1),
  ('usuario11@example.com', 'Miguel', 'Jiménez', 1),
  ('usuario12@example.com', 'Carmen', 'Reyes', 0),
  ('usuario13@example.com', 'Fernando', 'Diaz', 1),
  ('usuario14@example.com', 'Diana', 'Vargas', 1),
  ('usuario15@example.com', 'Andrés', 'Rojas', 1),
  ('usuario16@example.com', 'Carolina', 'Silva', 0),
  ('usuario17@example.com', 'Javier', 'Mendoza', 1),
  ('usuario18@example.com', 'Isabel', 'Guerrero', 0),
  ('usuario19@example.com', 'Santiago', 'Ortega', 1),
  ('usuario20@example.com', 'Paula', 'Ramos', 1),
  ('usuario21@example.com', 'Gabriel', 'Cruz', 0),
  ('usuario22@example.com', 'Valentina', 'Iglesias', 1),
  ('usuario23@example.com', 'Ricardo', 'Santos', 1),
  ('usuario24@example.com', 'Julia', 'Pacheco', 0),
  ('usuario25@example.com', 'Roberto', 'Castañeda', 1),
  ('usuario26@example.com', 'Florencia', 'Navarro', 0),
  ('usuario27@example.com', 'Diego', 'Cordero', 1),
  ('usuario28@example.com', 'Mariana', 'Villarreal', 0),
  ('usuario29@example.com', 'Emilio', 'Bustamante', 1),
  ('usuario30@example.com', 'Catalina', 'Zambrano', 1),
  ('usuario31@example.com', 'Alberto', 'Cervantes', 0),
  ('usuario32@example.com', 'Victoria', 'Benitez', 1),
  ('usuario33@example.com', 'Guillermo', 'Aguirre', 0),
  ('usuario34@example.com', 'Renata', 'Escobar', 1),
  ('usuario35@example.com', 'Eduardo', 'Vega', 1),
  ('usuario36@example.com', 'Alejandra', 'Solis', 0),
  ('usuario37@example.com', 'Raúl', 'Fuentes', 1),
  ('usuario38@example.com', 'Marina', 'Peralta', 0),
  ('usuario39@example.com', 'Hugo', 'Castaño', 1),
  ('usuario40@example.com', 'Jimena', 'Valdivia', 1),
  ('usuario41@example.com', 'Oscar', 'Franco', 0),
  ('usuario42@example.com', 'Beatriz', 'Roldán', 1),
  ('usuario43@example.com', 'Gustavo', 'Quintero', 0),
  ('usuario44@example.com', 'Adriana', 'Uribe', 1),
  ('usuario45@example.com', 'Leonardo', 'Zapata', 1),
  ('usuario46@example.com', 'Natalia', 'Becerra', 0),
  ('usuario47@example.com', 'Héctor', 'Orozco', 1),
  ('usuario48@example.com', 'Camila', 'Toro', 0),
  ('usuario49@example.com', 'Fernando', 'Guerra', 1),
  ('usuario50@example.com', 'Ana', 'Sepúlveda', 1);

INSERT INTO APLICACION (NOMBRE, DESCRIPCION, COSTO, CALIFICACION_ACTUAL, ID_CATEGORIA, VERSION_APP, RUTA_IMAGEN_PREVIA, RUTA_IMAGEN_ICONO)
VALUES
  ('Aplicacion 1', 'Descripcion de la Aplicacion 1', 5.25, 4, 3, '1.0', '', ''),
  ('Aplicacion 2', 'Descripcion de la Aplicacion 2', 0.99, 3, 2, '2.5', '', ''),
  ('Aplicacion 3', 'Descripcion de la Aplicacion 3', 8.75, 4, 6, '3.1', '', ''),
  ('Aplicacion 4', 'Descripcion de la Aplicacion 4', 12.45, 4, 7, '4.7', '', ''),
  ('Aplicacion 5', 'Descripcion de la Aplicacion 5', 2.50, 3, 4, '1.2', '', ''),
  ('Aplicacion 6', 'Descripcion de la Aplicacion 6', 1.75, 4, 5, '3.0', '', ''),
  ('Aplicacion 7', 'Descripcion de la Aplicacion 7', 6.80, 2, 2, '2.0', '', ''),
  ('Aplicacion 8', 'Descripcion de la Aplicacion 8', 11.00, 4, 8, '4.0', '', ''),
  ('Aplicacion 9', 'Descripcion de la Aplicacion 9', 0.10, 2, 1, '1.5', '', ''),
  ('Aplicacion 10', 'Descripcion de la Aplicacion 10', 3.40, 3, 3, '1.8', '', ''),
  ('Aplicacion 11', 'Descripcion de la Aplicacion 11', 5.90, 4, 5, '2.3', '', ''),
  ('Aplicacion 12', 'Descripcion de la Aplicacion 12', 9.20, 3, 4, '3.5', '', ''),
  ('Aplicacion 13', 'Descripcion de la Aplicacion 13', 0.50, 2, 1, '1.1', '', ''),
  ('Aplicacion 14', 'Descripcion de la Aplicacion 14', 7.30, 4, 7, '3.7', '', ''),
  ('Aplicacion 15', 'Descripcion de la Aplicacion 15', 13.75, 3, 6, '4.5', '', ''),
  ('Aplicacion 16', 'Descripcion de la Aplicacion 16', 4.90, 4, 3, '2.6', '', ''),
  ('Aplicacion 17', 'Descripcion de la Aplicacion 17', 2.15, 3, 2, '1.9', '', ''),
  ('Aplicacion 18', 'Descripcion de la Aplicacion 18', 10.60, 2, 5, '4.2', '', ''),
  ('Aplicacion 19', 'Descripcion de la Aplicacion 19', 0.90, 2, 1, '1.3', '', ''),
  ('Aplicacion 20', 'Descripcion de la Aplicacion 20', 6.00, 4, 4, '3.3', '', ''),
  ('Aplicacion 21', 'Descripcion de la Aplicacion 21', 3.15, 4, 3, '2.8', '', ''),
  ('Aplicacion 22', 'Descripcion de la Aplicacion 22', 9.80, 3, 6, '4.3', '', ''),
  ('Aplicacion 23', 'Descripcion de la Aplicacion 23', 0.30, 4, 2, '1.6', '', ''),
  ('Aplicacion 24', 'Descripcion de la Aplicacion 24', 7.80, 2, 7, '3.9', '', ''),
  ('Aplicacion 25', 'Descripcion de la Aplicacion 25', 14.50, 4, 8, '4.6', '', ''),
  ('Aplicacion 26', 'Descripcion de la Aplicacion 26', 5.10, 3, 4, '2.2', '', ''),
  ('Aplicacion 27', 'Descripcion de la Aplicacion 27', 2.35, 2, 3, '2.4', '', ''),
  ('Aplicacion 28', 'Descripcion de la Aplicacion 28', 10.90, 4, 5, '4.1', '', ''),
  ('Aplicacion 29', 'Descripcion de la Aplicacion 29', 1.10, 3, 1, '1.4', '', ''),
  ('Aplicacion 30', 'Descripcion de la Aplicacion 30', 6.40, 3, 2, '2.7', '', ''),
  ('Aplicacion 31', 'Descripcion de la Aplicacion 31', 4.90, 4, 4, '2.9', '', ''),
  ('Aplicacion 32', 'Descripcion de la Aplicacion 32', 11.20, 3, 6, '4.4', '', ''),
  ('Aplicacion 33', 'Descripcion de la Aplicacion 33', 0.70, 3, 3, '2.1', '', ''),
  ('Aplicacion 34', 'Descripcion de la Aplicacion 34', 8.30, 2, 5, '3.6', '', ''),
  ('Aplicacion 35', 'Descripcion de la Aplicacion 35', 15.00, 4, 7, '4.8', '', ''),
  ('Aplicacion 36', 'Descripcion de la Aplicacion 36', 5.50, 4, 8, '3.4', '', ''),
  ('Aplicacion 37', 'Descripcion de la Aplicacion 37', 3.85, 3, 1, '1.7', '', ''),
  ('Aplicacion 38', 'Descripcion de la Aplicacion 38', 9.50, 4, 2, '2.9', '', ''),
  ('Aplicacion 39', 'Descripcion de la Aplicacion 39', 0.20, 3, 3, '1.5', '', ''),
  ('Aplicacion 40', 'Descripcion de la Aplicacion 40', 7.10, 3, 5, '2.0', '', ''),
  ('Aplicacion 41', 'Descripcion de la Aplicacion 41', 13.40, 4, 6, '4.0', '', ''),
  ('Aplicacion 42', 'Descripcion de la Aplicacion 42', 4.40, 2, 4, '3.0', '', ''),
  ('Aplicacion 43', 'Descripcion de la Aplicacion 43', 1.95, 4, 3, '2.5', '', ''),
  ('Aplicacion 44', 'Descripcion de la Aplicacion 44', 10.10, 3, 7, '4.6', '', ''),
  ('Aplicacion 45', 'Descripcion de la Aplicacion 45', 0.80, 2, 1, '1.1', '', ''),
  ('Aplicacion 46', 'Descripcion de la Aplicacion 46', 6.70, 4, 2, '2.3', '', ''),
  ('Aplicacion 47', 'Descripcion de la Aplicacion 47', 12.00, 3, 8, '4.2', '', ''),
  ('Aplicacion 48', 'Descripcion de la Aplicacion 48', 5.25, 2, 6, '3.3', '', ''),
  ('Aplicacion 49', 'Descripcion de la Aplicacion 49', 2.40, 4, 5, '2.7', '', ''),
  ('Aplicacion 50', 'Descripcion de la Aplicacion 50', 8.75, 3, 3, '3.5', '', '');


INSERT INTO COMENTARIO (ID_APLICACION, ID_USUARIO, DESCRIPCION, FECHA_REGISTRO, ESTADO, CALIFICACION)
SELECT
  ROUND(RAND() * 49) + 1 as ID_APLICACION,
  ROUND(RAND() * 49) + 1 as ID_USUARIO,
  'Descripcion del comentario ' || (ROW_NUMBER() OVER ()) as DESCRIPCION,
  DATEADD('DAY', -ROUND(RAND() * 365), CURRENT_DATE) as FECHA_DE_REGISTRO,
  ROUND(RAND()) as ESTADO,
  ROUND(RAND() * 4) + 1 as CALIFICACION
FROM SYSTEM_RANGE(1, 200);