-- PUBLIC.CATEGORIA definition

-- Drop table

-- DROP TABLE PUBLIC.CATEGORIA;

CREATE SEQUENCE PUBLIC.SEQ_ID_CATEGORIA;

CREATE TABLE PUBLIC.CATEGORIA (
	ID_CATEGORIA INTEGER DEFAULT (NEXT VALUE FOR "PUBLIC"."SEQ_ID_CATEGORIA") NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(32) NOT NULL,
	DESCRIPCION VARCHAR(128),
	ESTADO INTEGER NOT NULL,
	CONSTRAINT CONSTRAINT_3 PRIMARY KEY (ID_CATEGORIA)
);
--CREATE UNIQUE INDEX PRIMARY_KEY_3 ON PUBLIC.CATEGORIA (ID_CATEGORIA);


-- PUBLIC.USUARIO definition

-- Drop table

-- DROP TABLE PUBLIC.USUARIO;

CREATE SEQUENCE PUBLIC.SEQ_ID_USUARIO;

CREATE TABLE PUBLIC.USUARIO (
	ID_USUARIO INTEGER DEFAULT (NEXT VALUE FOR "PUBLIC"."SEQ_ID_USUARIO") NOT NULL AUTO_INCREMENT,
	CORREO_ELECTRONICO VARCHAR(32) NOT NULL,
	NOMBRE VARCHAR(32),
	APELLIDO VARCHAR(32),
	ESTADO INTEGER NOT NULL,
	CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID_USUARIO)
);
--CREATE UNIQUE INDEX PRIMARY_KEY_2 ON PUBLIC.USUARIO (ID_USUARIO);


-- PUBLIC.APLICACION definition

-- Drop table

-- DROP TABLE PUBLIC.APLICACION;

CREATE SEQUENCE PUBLIC.SEQ_ID_APLICACION;

CREATE TABLE PUBLIC.APLICACION (
	ID_APLICACION INTEGER DEFAULT (NEXT VALUE FOR "PUBLIC"."SEQ_ID_APLICACION") NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(128) NOT NULL,
	DESCRIPCION VARCHAR(256),
	COSTO DECIMAL(4,2) NOT NULL,
	CALIFICACION_ACTUAL INTEGER NOT NULL,
	ID_CATEGORIA INTEGER,
	VERSION_APP VARCHAR(8),
	RUTA_IMAGEN_PREVIA VARCHAR(128) NOT NULL,
	RUTA_IMAGEN_ICONO VARCHAR(128) NOT NULL,
	CONSTRAINT CONSTRAINT_B PRIMARY KEY (ID_APLICACION),
	CONSTRAINT APLICACION_FK FOREIGN KEY (ID_CATEGORIA) REFERENCES PUBLIC.CATEGORIA(ID_CATEGORIA) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX APLICACION_FK_INDEX_D ON PUBLIC.APLICACION (ID_CATEGORIA);
CREATE UNIQUE INDEX PRIMARY_KEY_D ON PUBLIC.APLICACION (ID_APLICACION);


-- PUBLIC.COMENTARIO definition

-- Drop table

-- DROP TABLE PUBLIC.COMENTARIO;

CREATE SEQUENCE PUBLIC.SEQ_ID_COMENTARIO;

CREATE TABLE PUBLIC.COMENTARIO (
	ID_COMENTARIO INTEGER DEFAULT (NEXT VALUE FOR "PUBLIC"."SEQ_ID_COMENTARIO") NOT NULL AUTO_INCREMENT,
	ID_APLICACION INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	DESCRIPCION VARCHAR(512),
	FECHA_REGISTRO DATE NOT NULL,
	ESTADO INTEGER NOT NULL,
	CALIFICACION INTEGER,
	CONSTRAINT CONSTRAINT_BA PRIMARY KEY (ID_COMENTARIO),
	CONSTRAINT COMENTARIO_APLICACION_FK FOREIGN KEY (ID_APLICACION) REFERENCES PUBLIC.APLICACION(ID_APLICACION) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT COMENTARIO_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES PUBLIC.USUARIO(ID_USUARIO) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX COMENTARIO_APLICACION_FK_INDEX_F ON PUBLIC.COMENTARIO (ID_APLICACION);
CREATE INDEX COMENTARIO_USUARIO_FK_INDEX_F ON PUBLIC.COMENTARIO (ID_USUARIO);
CREATE UNIQUE INDEX PRIMARY_KEY_F ON PUBLIC.COMENTARIO (ID_COMENTARIO);